/* -*-c++-*-
 * @file: memory_map.hpp
 * @author: Dmitry Shpakov
 * @date: 2024/04/22
 * @licence: LGPL3 (see text at the end of a file)
 * @description: Symbols of memory sizes and origins generated by linker that
 *               could be used in source code.
 */

#pragma once

#include <cstdint>

using funcPtr = void (*)(void);

extern uint32_t __bootrom_start__;
extern uint32_t __bootrom_size__;
extern uint32_t __approm_start__;
extern uint32_t __approm_size__;
extern uint32_t __shared_start__;
extern uint32_t __shared_size__;
extern uint32_t __ram_start__;
extern uint32_t __ram_size__;
extern uint32_t __text_start__;
extern uint32_t __text_end__;
extern funcPtr __preinit_array_start__[];
extern funcPtr __preinit_array_end__[];
extern funcPtr __init_array_start__[];
extern funcPtr __init_array_end__[];
extern funcPtr __fini_array_start__[];
extern funcPtr __fini_array_end__[];
extern uint32_t __data_load__;
extern uint32_t __data_start__;
extern uint32_t __data_end__;
extern uint32_t __bss_start__;
extern uint32_t __bss_end__;
extern uint32_t __stack_top__;
extern uint32_t __heap_start__;

/*

Copyright © 2024 Dmitry Shpakov

This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; if not, see <http://www.gnu.org/licenses/>.

*/

